name: main
on: [workflow_dispatch]
jobs:
  check-markdown-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install -g prettier
      - run: prettier --check README.md CONTRIBUTING.md